---
title: "Data Exploration"
author: "Group 3"
date: "07.03.2021"
output: html_document
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(data.table)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
df <- read.csv("../../gen/data-preparation/output/transformed.csv'", sep=",")
```

# Overview of the data

### This is how the data set looks like:
```{r}
head(df)
```


### These are the column names and summary:
We can see that there are `r length(df$X)` vacancies.

```{r}
colnames(df)
```

```{r}
summary(df)
```

### Changing Scrape.Date column from character to date

```{r}
scrapedate <- as.Date(df$Scrape.Date, format = "%Y-%m-%d")
df$Scrape.Date <- scrapedate
```

### Cleaning the data
- lowering the column names

```{r}
names(df) <- tolower(names(df))
```


### Visualizing the frequency of job title, company, location, date
```{r}
ggplot(df, aes(title)) +
  geom_bar()

ggplot(df, aes(company)) +
  geom_bar()

ggplot(df, aes(location)) +
  geom_bar()

ggplot(df, aes(date)) +
  geom_bar()
```

